// src/lib/products.ts
export type Category = "Prendas" | "Accesorios";

export type Product = {
  id: number;
  name: string;
  price: number; // ARS
  img?: string;
  images?: string[];
  description?: string;
  inStock?: boolean;
  transferDiscount?: number;
  category: Category;
  isNew?: boolean;
  order?: number;
};

export const products: Product[] = [
  /* ====== 1–3 (ya tenías) ====== */
  {
    id: 1,
    name: "Baggy Denim Custom",
    price: 50000,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    isNew: true,
    img: "/products/1/cover.png",
    images: ["/products/1/cover.png"],
    description:
      "Baggy custom de denim con intervención artesanal. Cada pieza es única.",
    order: 10,
  },
  {
    id: 2,
    name: "Baggy Denim Custom",
    price: 50000,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    isNew: true,
    img: "/products/2/baggyRam.png",
    images: ["/products/2/baggyRam.png"],
    description: "Denim baggy intervenido por MANGATA. Upcycling con carácter.",
    order: 20,
  },
  {
    id: 3,
    name: "Baggy Foil",
    price: 55900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/3/jeanFoil.png",
    images: ["/products/3/jeanFoil.png", "/products/3/jeanFoil2.png"],
    description: "Baggy con detalles foil y tratamiento manual. Fit relajado.",
    order: 30,
  },

  /* ====== 4–31 (todos .png) ====== */
  {
    id: 4,
    name: "Canesú",
    price: 69900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/4/canesu.png",
    images: ["/products/4/canesu.png", "/products/4/canesu2.png"],
    description: "Jean con recorte canesú y juego de volúmenes.",
    order: 40,
  },
  {
    id: 5,
    name: "Pollera Foil",
    price: 58900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/5/polleraFoil.png",
    images: ["/products/5/polleraFoil.png", "/products/5/polleraFoil2.png"],
    description: "Pollera intervenida con foil. Brillo sobrio y artesanal.",
    order: 50,
  },
  {
    id: 6,
    name: "Buzo Alitas",
    price: 62900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/6/buzoAlitas.png",
    images: ["/products/6/buzoAlitas.png", "/products/6/buzoAlitas2.png"],
    description: "Buzo con apliques en forma de alas, mezcla de texturas.",
    order: 60,
  },
  {
    id: 7,
    name: "Campera Corderoy",
    price: 95900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/7/camperaCorderoy.png",
    images: [
      "/products/7/camperaCorderoy.png",
      "/products/7/camperaCorderoy2.png",
    ],
    description: "Campera de corderoy rearmada, cálida y versátil.",
    order: 70,
  },
  {
    id: 8,
    name: "Campera de Jean",
    price: 97900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/8/camperaDeJean.png",
    images: [
      "/products/8/camperaDeJean.png",
      "/products/8/camperaDeJean2.png",
      "/products/8/camperaDeJean3.png",
    ],
    description: "Clásica de denim con reconstrucción MANGATA.",
    order: 80,
  },
  {
    id: 9,
    name: "Blazer Cuadrillé",
    price: 98900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/9/blazerCuadri.png",
    images: [
      "/products/9/blazerCuadri.png",
      "/products/9/blazerCuadri2.png",
      "/products/9/blazerCuadri3.png",
    ],
    description: "Sastrero intervenido, patrón cuadrillé, fit moderno.",
    order: 90,
  },
  {
    id: 10,
    name: "Sastrero Baggy Black",
    price: 89900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/10/sastreroBaggyBlack.png",
    images: ["/products/10/sastreroBaggyBlack.png"],
    description: "Pantalón sastrero baggy negro, líneas limpias.",
    order: 100,
  },
  {
    id: 11,
    name: "Bermuda Tribal",
    price: 69900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/11/bermudaTribal.png",
    images: ["/products/11/bermudaTribal.png"],
    description: "Bermuda denim con apliques tribales.",
    order: 110,
  },
  {
    id: 12,
    name: "Mono Black",
    price: 109900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/12/monoBlack.png",
    images: ["/products/12/monoBlack.png"],
    description: "Mono negro minimal con ajuste cómodo.",
    order: 120,
  },

  /* ====== ACCESORIOS reales (normalizados a ASCII) ====== */
  {
    id: 13,
    name: "Corbata Corazón",
    price: 31900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Accesorios",
    img: "/products/13/corbataCorazon.png",
    images: ["/products/13/corbataCorazon.png"],
    description: "Corbata upcycled con aplique corazón.",
    order: 130,
  },
  {
    id: 18,
    name: "Choker Metalizado",
    price: 23900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Accesorios",
    img: "/products/18/chockerMetalizado.png",
    images: ["/products/18/chockerMetalizado.png"],
    description: "Gargantilla metálica reciclada. Statement piece.",
    order: 180,
  },
  {
    id: 22,
    name: "Bag Croco",
    price: 69900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Accesorios",
    img: "/products/22/bagCroco.png",
    images: ["/products/22/bagCroco.png"],
    description: "Bolso textura croco upcycled. Compacto y robusto.",
    order: 220,
  },
  {
    id: 27,
    name: "Cinto Utilitario",
    price: 35900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Accesorios",
    img: "/products/27/cintoUtilitario.png",
    images: ["/products/27/cintoUtilitario.png"],
    description: "Cinturón utilitario reforzado, regulable.",
    order: 270,
  },
  {
    id: 31,
    name: "Pasamontañas Friza",
    price: 29900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Accesorios",
    // ⚠️ archivo en ASCII: pasamontanasFriza.png (sin ñ)
    img: "/products/31/pasamontañasFriza.png",
    images: ["/products/31/pasamontañasFriza.png"],
    description: "Pasamontañas de friza. Abrigo y actitud.",
    order: 310,
  },

  /* ====== resto de prendas ====== */
  {
    id: 14,
    name: "Top Cruz",
    price: 45900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/14/topCruz.png",
    images: ["/products/14/topCruz.png"],
    description: "Top cruzado con recortes y ajuste firme.",
    order: 140,
  },
  {
    id: 15,
    name: "Musculosa Red",
    price: 39900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/15/musculosaRed.png",
    images: ["/products/15/musculosaRed.png"],
    description: "Musculosa con red y contraste de texturas.",
    order: 150,
  },
  {
    id: 16,
    name: "Vestido Microtul",
    price: 95900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/16/vestidoMicrotul.png",
    images: ["/products/16/vestidoMicrotul.png"],
    description: "Vestido etéreo de microtul. Capas y movimiento.",
    order: 160,
  },
  {
    id: 17,
    name: "Camisa Crop Cuadrillé",
    price: 56900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/17/camisaCropCuadrille.png",
    images: ["/products/17/camisaCropCuadrille.png"],
    description: "Camisa recortada con patrón cuadrillé.",
    order: 170,
  },
  {
    id: 19,
    name: "Mini Volado",
    price: 52900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/19/miniVolado.png",
    images: ["/products/19/miniVolado.png"],
    description: "Falda mini con volado y corte upcycled.",
    order: 190,
  },
  {
    id: 20,
    name: "Corpiño Óxido",
    price: 44900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    // ASCII en archivo: corpiñoOxido.png (sin ñ/acentos)
    img: "/products/20/corpiñoOxido.png",
    images: ["/products/20/corpiñoOxido.png"],
    description: "Top/corpiño con efectos de óxido controlado.",
    order: 200,
  },
  {
    id: 21,
    name: "Musculosa Cute",
    price: 38900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/21/musculosaCute.png",
    images: ["/products/21/musculosaCute.png"],
    description: "Musculosa ligera con detalles delicados.",
    order: 210,
  },
  {
    id: 23,
    name: "Baggy Tribal",
    price: 57900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/23/baggyTribal.png",
    images: ["/products/23/baggyTribal.png"],
    description: "Baggy con apliques gráficos tribales.",
    order: 230,
  },
  {
    id: 24,
    name: "Hood Denim",
    price: 82900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/24/hoodDenim.png",
    images: ["/products/24/hoodDenim.png"],
    description: "Hoodie intervenido con denim. Híbrido textil.",
    order: 240,
  },
  {
    id: 25,
    name: "Boxy Black",
    price: 44900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/25/boxyBlack.png",
    images: ["/products/25/boxyBlack.png"],
    description: "Remera boxy negra con caída pesada.",
    order: 250,
  },
  {
    id: 26,
    name: "Top Picos",
    price: 46900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/26/topPicos.png",
    images: ["/products/26/topPicos.png"],
    description: "Top con picos y recortes geométricos.",
    order: 260,
  },
  {
    id: 28,
    name: "Falda Red Plata",
    price: 56900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/28/faldaRedPlata.png",
    images: ["/products/28/faldaRedPlata.png"],
    description: "Mini falda con red plateada y capas.",
    order: 280,
  },
  {
    id: 29,
    name: "Micro Mini",
    price: 51900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/29/microMini.png",
    images: ["/products/29/microMini.png"],
    description: "Micro mini con fit ceñido.",
    order: 290,
  },
  {
    id: 30,
    name: "Musculosa Trash",
    price: 38900,
    inStock: true,
    transferDiscount: 0.1,
    category: "Prendas",
    img: "/products/30/musculosaTrash.png",
    images: ["/products/30/musculosaTrash.png"],
    description: "Musculosa con estética raw/trash.",
    order: 300,
  },
];
