\getenv app_password MANGATA_APP_PASSWORD
CREATE ROLE mangata_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'app_password';
REVOKE ALL ON DATABASE mangata FROM PUBLIC;
GRANT CONNECT ON DATABASE mangata TO mangata_app;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO mangata_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO mangata_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO mangata_app;
