# BEGIN MANGATA HTTP
server {
    listen 80;
    server_name mangata.com.ar www.mangata.com.ar;

    location ^~ /.well-known/acme-challenge/ {
        alias /var/www/html/public/.well-known/acme-challenge/;
        try_files $uri =404;
    }

    location / {
        return 301 https://mangata.com.ar$request_uri;
    }
}
# END MANGATA HTTP
